packaging_format = 2

id = "backdrop"
name = "Backdrop"
description.en = "Easy-to-use CMS for building professional websites"
description.fr = "CMS facile à utiliser pour créer des sites Web professionnels"

version = "1.28.2~ynh1"

maintainers = []

[upstream]
license = "GPL-2.0"
website = "https://backdropcms.org/"
demo = "https://backdropcms.org/demo"
userdoc = "https://backdropcms.org/user-guide"
code = "https://github.com/backdrop/backdrop"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"
[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/backdrop"

    [install.init_main_permission]
    help.en = "If enabled, Backdrop will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Backdrop sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/backdrop/backdrop/archive/refs/tags/1.28.2.tar.gz"
        sha256 = "2eb64dde17889ed373c7e3b515b77d9990836ca6a0e5572f9dffc9d2b2279682"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.0-mbstring php8.0-xmlrpc php8.0-soap php8.0-mysql php8.0-gd php8.0-xml php8.0-cli php8.0-zip"

    [resources.database]
    type = "mysql"
