#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# CONFIGURE TTRSS
#=================================================
ynh_script_progression "Configuring $app..."

salt="$(ynh_string_random --length=30)"
dir="__DIR__"
ynh_config_add --template="settings.example.php" --destination="$install_dir/settings.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
